// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tracking_backward_pass_2_Pipeline_VITIS_LOOP_86_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_i,
        p_col_p1_address0,
        p_col_p1_ce0,
        p_col_p1_we0,
        p_col_p1_d0,
        p_col_p1_address1,
        p_col_p1_ce1,
        p_col_p1_we1,
        p_col_p1_d1,
        p_1_address0,
        p_1_ce0,
        p_1_q0,
        p_1_address1,
        p_1_ce1,
        p_1_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] mul_i;
output  [3:0] p_col_p1_address0;
output   p_col_p1_ce0;
output   p_col_p1_we0;
output  [31:0] p_col_p1_d0;
output  [3:0] p_col_p1_address1;
output   p_col_p1_ce1;
output   p_col_p1_we1;
output  [31:0] p_col_p1_d1;
output  [6:0] p_1_address0;
output   p_1_ce0;
input  [31:0] p_1_q0;
output  [6:0] p_1_address1;
output   p_1_ce1;
input  [31:0] p_1_q1;

reg ap_idle;
reg[3:0] p_col_p1_address0;
reg p_col_p1_ce0;
reg p_col_p1_we0;
reg[3:0] p_col_p1_address1;
reg p_col_p1_ce1;
reg p_col_p1_we1;
reg[6:0] p_1_address0;
reg p_1_ce0;
reg[6:0] p_1_address1;
reg p_1_ce1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln86_fu_142_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] i_54_reg_262;
reg   [0:0] icmp_ln86_reg_269;
wire   [3:0] or_ln86_fu_163_p2;
reg   [3:0] or_ln86_reg_278;
wire   [3:0] or_ln86_16_fu_203_p2;
reg   [3:0] or_ln86_16_reg_288;
wire    ap_block_pp0_stage1_11001;
wire   [3:0] or_ln86_17_fu_222_p2;
reg   [3:0] or_ln86_17_reg_298;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln88_fu_158_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln88_74_fu_179_p1;
wire   [63:0] i_60_cast8_fu_195_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln88_72_fu_199_p1;
wire   [63:0] zext_ln88_77_fu_217_p1;
wire   [63:0] zext_ln88_80_fu_236_p1;
wire   [63:0] zext_ln88_75_fu_241_p1;
wire   [63:0] zext_ln88_78_fu_245_p1;
reg   [3:0] i_fu_40;
wire   [3:0] add_ln86_fu_184_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_54;
wire   [6:0] i_60_cast2_fu_148_p1;
wire   [6:0] add_ln88_fu_152_p2;
wire   [6:0] zext_ln88_73_fu_169_p1;
wire   [6:0] add_ln88_23_fu_173_p2;
wire   [6:0] zext_ln88_76_fu_208_p1;
wire   [6:0] add_ln88_24_fu_212_p2;
wire   [6:0] zext_ln88_79_fu_227_p1;
wire   [6:0] add_ln88_25_fu_231_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

tracking_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln86_fu_142_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_40 <= add_ln86_fu_184_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_40 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_54_reg_262 <= ap_sig_allocacmp_i_54;
        icmp_ln86_reg_269 <= icmp_ln86_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln86_reg_269 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln86_16_reg_288[0] <= or_ln86_16_fu_203_p2[0];
or_ln86_16_reg_288[3 : 2] <= or_ln86_16_fu_203_p2[3 : 2];
        or_ln86_17_reg_298[3 : 2] <= or_ln86_17_fu_222_p2[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln86_fu_142_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln86_reg_278[3 : 1] <= or_ln86_fu_163_p2[3 : 1];
    end
end

always @ (*) begin
    if (((icmp_ln86_fu_142_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_54 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_54 = i_fu_40;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_1_address0 = zext_ln88_80_fu_236_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_1_address0 = zext_ln88_74_fu_179_p1;
        end else begin
            p_1_address0 = 'bx;
        end
    end else begin
        p_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            p_1_address1 = zext_ln88_77_fu_217_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_1_address1 = zext_ln88_fu_158_p1;
        end else begin
            p_1_address1 = 'bx;
        end
    end else begin
        p_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_1_ce0 = 1'b1;
    end else begin
        p_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_1_ce1 = 1'b1;
    end else begin
        p_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_col_p1_address0 = zext_ln88_78_fu_245_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_col_p1_address0 = zext_ln88_72_fu_199_p1;
    end else begin
        p_col_p1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_col_p1_address1 = zext_ln88_75_fu_241_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_col_p1_address1 = i_60_cast8_fu_195_p1;
    end else begin
        p_col_p1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_col_p1_ce0 = 1'b1;
    end else begin
        p_col_p1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_col_p1_ce1 = 1'b1;
    end else begin
        p_col_p1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln86_reg_269 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_col_p1_we0 = 1'b1;
    end else begin
        p_col_p1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln86_reg_269 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_col_p1_we1 = 1'b1;
    end else begin
        p_col_p1_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln86_fu_184_p2 = (ap_sig_allocacmp_i_54 + 4'd4);

assign add_ln88_23_fu_173_p2 = (zext_ln88_73_fu_169_p1 + mul_i);

assign add_ln88_24_fu_212_p2 = (zext_ln88_76_fu_208_p1 + mul_i);

assign add_ln88_25_fu_231_p2 = (zext_ln88_79_fu_227_p1 + mul_i);

assign add_ln88_fu_152_p2 = (i_60_cast2_fu_148_p1 + mul_i);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_60_cast2_fu_148_p1 = ap_sig_allocacmp_i_54;

assign i_60_cast8_fu_195_p1 = i_54_reg_262;

assign icmp_ln86_fu_142_p2 = ((ap_sig_allocacmp_i_54 == 4'd12) ? 1'b1 : 1'b0);

assign or_ln86_16_fu_203_p2 = (i_54_reg_262 | 4'd2);

assign or_ln86_17_fu_222_p2 = (i_54_reg_262 | 4'd3);

assign or_ln86_fu_163_p2 = (ap_sig_allocacmp_i_54 | 4'd1);

assign p_col_p1_d0 = p_1_q0;

assign p_col_p1_d1 = p_1_q1;

assign zext_ln88_72_fu_199_p1 = or_ln86_reg_278;

assign zext_ln88_73_fu_169_p1 = or_ln86_fu_163_p2;

assign zext_ln88_74_fu_179_p1 = add_ln88_23_fu_173_p2;

assign zext_ln88_75_fu_241_p1 = or_ln86_16_reg_288;

assign zext_ln88_76_fu_208_p1 = or_ln86_16_fu_203_p2;

assign zext_ln88_77_fu_217_p1 = add_ln88_24_fu_212_p2;

assign zext_ln88_78_fu_245_p1 = or_ln86_17_reg_298;

assign zext_ln88_79_fu_227_p1 = or_ln86_17_fu_222_p2;

assign zext_ln88_80_fu_236_p1 = add_ln88_25_fu_231_p2;

assign zext_ln88_fu_158_p1 = add_ln88_fu_152_p2;

always @ (posedge ap_clk) begin
    or_ln86_reg_278[0] <= 1'b1;
    or_ln86_16_reg_288[1] <= 1'b1;
    or_ln86_17_reg_298[1:0] <= 2'b11;
end

endmodule //tracking_backward_pass_2_Pipeline_VITIS_LOOP_86_1
