// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tracking_update_linear_cost (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        znew_1_address0,
        znew_1_ce0,
        znew_1_q0,
        y_1_address0,
        y_1_ce0,
        y_1_q0,
        m1_1_address0,
        m1_1_ce0,
        m1_1_we0,
        m1_1_d0,
        m1_1_q0,
        tiny_rho,
        r_1_address0,
        r_1_ce0,
        r_1_we0,
        r_1_d0,
        vnew_1_address0,
        vnew_1_ce0,
        vnew_1_q0,
        vnew_1_address1,
        vnew_1_ce1,
        vnew_1_q1,
        g_1_address0,
        g_1_ce0,
        g_1_q0,
        g_1_address1,
        g_1_ce1,
        g_1_q1,
        s1_1_address0,
        s1_1_ce0,
        s1_1_we0,
        s1_1_d0,
        s1_1_q0,
        s2_1_address0,
        s2_1_ce0,
        s2_1_we0,
        s2_1_d0,
        s2_1_q0,
        q_1_address0,
        q_1_ce0,
        q_1_we0,
        q_1_d0,
        q_1_q0,
        q_1_address1,
        q_1_ce1,
        q_1_we1,
        q_1_d1,
        q_1_q1,
        Xref_1_address0,
        Xref_1_ce0,
        Xref_1_q0,
        Xref_1_address1,
        Xref_1_ce1,
        Xref_1_q1,
        p_1_address0,
        p_1_ce0,
        p_1_we0,
        p_1_d0,
        p_1_q0,
        p_1_address1,
        p_1_ce1,
        p_1_we1,
        p_1_d1,
        p_1_q1,
        tiny_x1_address0,
        tiny_x1_ce0,
        tiny_x1_we0,
        tiny_x1_d0,
        tiny_x1_q0,
        tiny_x2_address0,
        tiny_x2_ce0,
        tiny_x2_we0,
        tiny_x2_d0,
        tiny_x2_q0,
        PinfT_1_address0,
        PinfT_1_ce0,
        PinfT_1_q0,
        PinfT_1_address1,
        PinfT_1_ce1,
        PinfT_1_q1,
        tiny_x3_address0,
        tiny_x3_ce0,
        tiny_x3_we0,
        tiny_x3_d0,
        tiny_x3_q0,
        tiny_Q_address0,
        tiny_Q_ce0,
        tiny_Q_q0
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] znew_1_address0;
output   znew_1_ce0;
input  [31:0] znew_1_q0;
output  [5:0] y_1_address0;
output   y_1_ce0;
input  [31:0] y_1_q0;
output  [5:0] m1_1_address0;
output   m1_1_ce0;
output   m1_1_we0;
output  [31:0] m1_1_d0;
input  [31:0] m1_1_q0;
input  [31:0] tiny_rho;
output  [5:0] r_1_address0;
output   r_1_ce0;
output   r_1_we0;
output  [31:0] r_1_d0;
output  [6:0] vnew_1_address0;
output   vnew_1_ce0;
input  [31:0] vnew_1_q0;
output  [6:0] vnew_1_address1;
output   vnew_1_ce1;
input  [31:0] vnew_1_q1;
output  [6:0] g_1_address0;
output   g_1_ce0;
input  [31:0] g_1_q0;
output  [6:0] g_1_address1;
output   g_1_ce1;
input  [31:0] g_1_q1;
output  [6:0] s1_1_address0;
output   s1_1_ce0;
output   s1_1_we0;
output  [31:0] s1_1_d0;
input  [31:0] s1_1_q0;
output  [6:0] s2_1_address0;
output   s2_1_ce0;
output   s2_1_we0;
output  [31:0] s2_1_d0;
input  [31:0] s2_1_q0;
output  [6:0] q_1_address0;
output   q_1_ce0;
output   q_1_we0;
output  [31:0] q_1_d0;
input  [31:0] q_1_q0;
output  [6:0] q_1_address1;
output   q_1_ce1;
output   q_1_we1;
output  [31:0] q_1_d1;
input  [31:0] q_1_q1;
output  [6:0] Xref_1_address0;
output   Xref_1_ce0;
input  [31:0] Xref_1_q0;
output  [6:0] Xref_1_address1;
output   Xref_1_ce1;
input  [31:0] Xref_1_q1;
output  [6:0] p_1_address0;
output   p_1_ce0;
output   p_1_we0;
output  [31:0] p_1_d0;
input  [31:0] p_1_q0;
output  [6:0] p_1_address1;
output   p_1_ce1;
output   p_1_we1;
output  [31:0] p_1_d1;
input  [31:0] p_1_q1;
output  [3:0] tiny_x1_address0;
output   tiny_x1_ce0;
output   tiny_x1_we0;
output  [31:0] tiny_x1_d0;
input  [31:0] tiny_x1_q0;
output  [3:0] tiny_x2_address0;
output   tiny_x2_ce0;
output   tiny_x2_we0;
output  [31:0] tiny_x2_d0;
input  [31:0] tiny_x2_q0;
output  [7:0] PinfT_1_address0;
output   PinfT_1_ce0;
input  [31:0] PinfT_1_q0;
output  [7:0] PinfT_1_address1;
output   PinfT_1_ce1;
input  [31:0] PinfT_1_q1;
output  [3:0] tiny_x3_address0;
output   tiny_x3_ce0;
output   tiny_x3_we0;
output  [31:0] tiny_x3_d0;
input  [31:0] tiny_x3_q0;
output  [3:0] tiny_Q_address0;
output   tiny_Q_ce0;
input  [31:0] tiny_Q_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg znew_1_ce0;
reg y_1_ce0;
reg[5:0] m1_1_address0;
reg m1_1_ce0;
reg m1_1_we0;
reg r_1_ce0;
reg r_1_we0;
reg[6:0] vnew_1_address0;
reg vnew_1_ce0;
reg vnew_1_ce1;
reg[6:0] g_1_address0;
reg g_1_ce0;
reg g_1_ce1;
reg[6:0] s1_1_address0;
reg s1_1_ce0;
reg s1_1_we0;
reg[31:0] s1_1_d0;
reg[6:0] s2_1_address0;
reg s2_1_ce0;
reg s2_1_we0;
reg[6:0] q_1_address0;
reg q_1_ce0;
reg q_1_we0;
reg[31:0] q_1_d0;
reg[6:0] q_1_address1;
reg q_1_ce1;
reg q_1_we1;
reg[6:0] Xref_1_address0;
reg Xref_1_ce0;
reg[6:0] Xref_1_address1;
reg Xref_1_ce1;
reg[3:0] tiny_x1_address0;
reg tiny_x1_ce0;
reg tiny_x1_we0;
reg[31:0] tiny_x1_d0;

(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] add_ln167_fu_329_p2;
reg   [3:0] add_ln167_reg_517;
wire    ap_CS_fsm_state2;
wire   [5:0] tmp_fu_335_p3;
reg   [5:0] tmp_reg_522;
wire   [0:0] icmp_ln167_fu_323_p2;
wire   [31:0] bitcast_ln116_1_fu_357_p1;
reg   [31:0] bitcast_ln116_1_reg_539;
wire   [2:0] add_ln168_fu_376_p2;
reg   [2:0] add_ln168_reg_547;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln169_fu_387_p1;
reg   [63:0] zext_ln169_reg_552;
wire   [0:0] icmp_ln168_fu_370_p2;
wire    ap_CS_fsm_state4;
wire   [3:0] add_ln159_fu_406_p2;
reg   [3:0] add_ln159_reg_580;
wire    ap_CS_fsm_state6;
wire   [5:0] tmp_s_fu_412_p3;
reg   [5:0] tmp_s_reg_585;
wire   [0:0] icmp_ln159_fu_400_p2;
wire   [2:0] add_ln160_fu_435_p2;
reg   [2:0] add_ln160_reg_600;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln161_fu_446_p1;
reg   [63:0] zext_ln161_reg_605;
wire   [0:0] icmp_ln160_fu_429_p2;
wire   [31:0] mul5_i_i_fu_310_p2;
reg   [31:0] mul5_i_i_reg_615;
wire    ap_CS_fsm_state8;
wire   [6:0] empty_66_fu_494_p2;
reg   [6:0] empty_66_reg_623;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln215_fu_458_p2;
reg   [3:0] xref_col_address0;
reg    xref_col_ce0;
reg    xref_col_we0;
wire   [31:0] xref_col_q0;
reg    xref_col_ce1;
reg    xref_col_we1;
reg   [3:0] q_col_address0;
reg    q_col_ce0;
reg    q_col_we0;
reg   [31:0] q_col_d0;
wire   [31:0] q_col_q0;
reg   [3:0] q_col_address1;
reg    q_col_ce1;
reg    q_col_we1;
wire   [31:0] q_col_q1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_ready;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_d0;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_address1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_ce1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_we1;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_d1;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_ce0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_address1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_ce1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_ready;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_d0;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_address1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_ce1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_we1;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_d1;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_ce0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_address1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_ce1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_ready;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_vnew_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_vnew_1_ce0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_g_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_g_1_ce0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_d0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_din0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_din1;
wire   [0:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_opcode;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_ce;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_ready;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_xref_col_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_xref_col_ce0;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_Q_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_Q_ce0;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_d0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_ready;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_d0;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_tiny_x1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_tiny_x1_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_ready;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_ce0;
wire   [3:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_address1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_ce1;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_d0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_address1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_ce1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_we1;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_d1;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_ready;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s1_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s1_1_ce0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_d0;
wire    grp_update_linear_cost_4_fu_263_ap_start;
wire    grp_update_linear_cost_4_fu_263_ap_done;
wire    grp_update_linear_cost_4_fu_263_ap_idle;
wire    grp_update_linear_cost_4_fu_263_ap_ready;
wire   [6:0] grp_update_linear_cost_4_fu_263_vnew_1_address0;
wire    grp_update_linear_cost_4_fu_263_vnew_1_ce0;
wire   [6:0] grp_update_linear_cost_4_fu_263_vnew_1_address1;
wire    grp_update_linear_cost_4_fu_263_vnew_1_ce1;
wire   [6:0] grp_update_linear_cost_4_fu_263_g_1_address0;
wire    grp_update_linear_cost_4_fu_263_g_1_ce0;
wire   [6:0] grp_update_linear_cost_4_fu_263_g_1_address1;
wire    grp_update_linear_cost_4_fu_263_g_1_ce1;
wire   [6:0] grp_update_linear_cost_4_fu_263_Xref_1_address0;
wire    grp_update_linear_cost_4_fu_263_Xref_1_ce0;
wire   [6:0] grp_update_linear_cost_4_fu_263_Xref_1_address1;
wire    grp_update_linear_cost_4_fu_263_Xref_1_ce1;
wire   [6:0] grp_update_linear_cost_4_fu_263_p_1_address0;
wire    grp_update_linear_cost_4_fu_263_p_1_ce0;
wire    grp_update_linear_cost_4_fu_263_p_1_we0;
wire   [31:0] grp_update_linear_cost_4_fu_263_p_1_d0;
wire   [6:0] grp_update_linear_cost_4_fu_263_p_1_address1;
wire    grp_update_linear_cost_4_fu_263_p_1_ce1;
wire    grp_update_linear_cost_4_fu_263_p_1_we1;
wire   [31:0] grp_update_linear_cost_4_fu_263_p_1_d1;
wire   [3:0] grp_update_linear_cost_4_fu_263_tiny_x1_address0;
wire    grp_update_linear_cost_4_fu_263_tiny_x1_ce0;
wire    grp_update_linear_cost_4_fu_263_tiny_x1_we0;
wire   [31:0] grp_update_linear_cost_4_fu_263_tiny_x1_d0;
wire   [3:0] grp_update_linear_cost_4_fu_263_tiny_x2_address0;
wire    grp_update_linear_cost_4_fu_263_tiny_x2_ce0;
wire    grp_update_linear_cost_4_fu_263_tiny_x2_we0;
wire   [31:0] grp_update_linear_cost_4_fu_263_tiny_x2_d0;
wire   [7:0] grp_update_linear_cost_4_fu_263_PinfT_1_address0;
wire    grp_update_linear_cost_4_fu_263_PinfT_1_ce0;
wire   [7:0] grp_update_linear_cost_4_fu_263_PinfT_1_address1;
wire    grp_update_linear_cost_4_fu_263_PinfT_1_ce1;
wire   [3:0] grp_update_linear_cost_4_fu_263_tiny_x3_address0;
wire    grp_update_linear_cost_4_fu_263_tiny_x3_ce0;
wire    grp_update_linear_cost_4_fu_263_tiny_x3_we0;
wire   [31:0] grp_update_linear_cost_4_fu_263_tiny_x3_d0;
wire   [31:0] grp_update_linear_cost_4_fu_263_grp_fu_303_p_din0;
wire   [31:0] grp_update_linear_cost_4_fu_263_grp_fu_303_p_din1;
wire   [1:0] grp_update_linear_cost_4_fu_263_grp_fu_303_p_opcode;
wire    grp_update_linear_cost_4_fu_263_grp_fu_303_p_ce;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_ready;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_q_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_q_1_ce0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s2_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s2_1_ce0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_d0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_din0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_din1;
wire   [0:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_opcode;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_ce;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_done;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_idle;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_ready;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_s1_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_s1_1_ce0;
wire   [6:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_address0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_ce0;
wire    grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_we0;
wire   [31:0] grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_d0;
reg   [2:0] j_reg_182;
wire    ap_CS_fsm_state5;
reg   [2:0] j_8_reg_193;
wire    ap_CS_fsm_state9;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start_reg;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start_reg;
wire    ap_CS_fsm_state18;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
reg    grp_update_linear_cost_4_fu_263_ap_start_reg;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start_reg;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
reg    grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start_reg;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
reg   [3:0] i_fu_102;
reg   [3:0] i_11_fu_114;
reg   [3:0] i_12_fu_118;
wire   [3:0] add_ln215_fu_464_p2;
wire   [31:0] grp_fu_303_p2;
reg   [31:0] grp_fu_303_p0;
reg   [31:0] grp_fu_303_p1;
wire   [31:0] bitcast_ln116_fu_347_p1;
wire   [31:0] xor_ln116_fu_351_p2;
wire   [5:0] zext_ln168_fu_366_p1;
wire   [5:0] add_ln169_fu_382_p2;
wire   [5:0] zext_ln160_fu_425_p1;
wire   [5:0] add_ln161_fu_441_p2;
wire   [2:0] empty_65_fu_470_p1;
wire   [5:0] p_shl1_fu_482_p3;
wire   [6:0] p_shl_fu_474_p3;
wire   [6:0] p_shl1_cast_fu_490_p1;
reg   [1:0] grp_fu_303_opcode;
reg    grp_fu_303_ce;
reg   [23:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_block_state11_on_subcall_done;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_block_state20_on_subcall_done;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_4_fu_263_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start_reg = 1'b0;
#0 grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start_reg = 1'b0;
end

tracking_update_linear_cost_xref_col_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
xref_col_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(xref_col_address0),
    .ce0(xref_col_ce0),
    .we0(xref_col_we0),
    .d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_d0),
    .q0(xref_col_q0),
    .address1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_address1),
    .ce1(xref_col_ce1),
    .we1(xref_col_we1),
    .d1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_d1)
);

tracking_forward_pass_2_x_col_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
q_col_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(q_col_address0),
    .ce0(q_col_ce0),
    .we0(q_col_we0),
    .d0(q_col_d0),
    .q0(q_col_q0),
    .address1(q_col_address1),
    .ce1(q_col_ce1),
    .we1(q_col_we1),
    .d1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_d1),
    .q1(q_col_q1)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_86_1 grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_ready),
    .empty(empty_66_reg_623),
    .xref_col_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_address0),
    .xref_col_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_ce0),
    .xref_col_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_we0),
    .xref_col_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_d0),
    .xref_col_address1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_address1),
    .xref_col_ce1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_ce1),
    .xref_col_we1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_we1),
    .xref_col_d1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_d1),
    .Xref_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_address0),
    .Xref_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_ce0),
    .Xref_1_q0(Xref_1_q0),
    .Xref_1_address1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_address1),
    .Xref_1_ce1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_ce1),
    .Xref_1_q1(Xref_1_q1)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_86_17 grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_ready),
    .empty(empty_66_reg_623),
    .q_col_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_address0),
    .q_col_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_ce0),
    .q_col_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_we0),
    .q_col_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_d0),
    .q_col_address1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_address1),
    .q_col_ce1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_ce1),
    .q_col_we1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_we1),
    .q_col_d1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_d1),
    .q_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_address0),
    .q_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_ce0),
    .q_1_q0(q_1_q0),
    .q_1_address1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_address1),
    .q_1_ce1(grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_ce1),
    .q_1_q1(q_1_q1)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2 grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_ready),
    .vnew_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_vnew_1_address0),
    .vnew_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_vnew_1_ce0),
    .vnew_1_q0(vnew_1_q0),
    .g_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_g_1_address0),
    .g_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_g_1_ce0),
    .g_1_q0(g_1_q0),
    .s1_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_address0),
    .s1_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_ce0),
    .s1_1_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_we0),
    .s1_1_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_d0),
    .grp_fu_303_p_din0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_din0),
    .grp_fu_303_p_din1(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_din1),
    .grp_fu_303_p_opcode(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_opcode),
    .grp_fu_303_p_dout0(grp_fu_303_p2),
    .grp_fu_303_p_ce(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_ce)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_99_2 grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_ready),
    .xref_col_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_xref_col_address0),
    .xref_col_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_xref_col_ce0),
    .xref_col_q0(xref_col_q0),
    .tiny_Q_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_Q_address0),
    .tiny_Q_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_Q_ce0),
    .tiny_Q_q0(tiny_Q_q0),
    .tiny_x1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_address0),
    .tiny_x1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_ce0),
    .tiny_x1_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_we0),
    .tiny_x1_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_d0)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_72_2 grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_ready),
    .q_col_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_address0),
    .q_col_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_ce0),
    .q_col_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_we0),
    .q_col_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_d0),
    .tiny_x1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_tiny_x1_address0),
    .tiny_x1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_tiny_x1_ce0),
    .tiny_x1_q0(tiny_x1_q0)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_93_1 grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_ready),
    .q_col_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_address0),
    .q_col_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_ce0),
    .q_col_q0(q_col_q0),
    .q_col_address1(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_address1),
    .q_col_ce1(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_ce1),
    .q_col_q1(q_col_q1),
    .empty(empty_66_reg_623),
    .q_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_address0),
    .q_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_ce0),
    .q_1_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_we0),
    .q_1_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_d0),
    .q_1_address1(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_address1),
    .q_1_ce1(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_ce1),
    .q_1_we1(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_we1),
    .q_1_d1(grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_d1)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2 grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_ready),
    .tiny_rho_load(tiny_rho),
    .s1_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s1_1_address0),
    .s1_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s1_1_ce0),
    .s1_1_q0(s1_1_q0),
    .s2_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_address0),
    .s2_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_ce0),
    .s2_1_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_we0),
    .s2_1_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_d0)
);

tracking_update_linear_cost_4 grp_update_linear_cost_4_fu_263(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_4_fu_263_ap_start),
    .ap_done(grp_update_linear_cost_4_fu_263_ap_done),
    .ap_idle(grp_update_linear_cost_4_fu_263_ap_idle),
    .ap_ready(grp_update_linear_cost_4_fu_263_ap_ready),
    .vnew_1_address0(grp_update_linear_cost_4_fu_263_vnew_1_address0),
    .vnew_1_ce0(grp_update_linear_cost_4_fu_263_vnew_1_ce0),
    .vnew_1_q0(vnew_1_q0),
    .vnew_1_address1(grp_update_linear_cost_4_fu_263_vnew_1_address1),
    .vnew_1_ce1(grp_update_linear_cost_4_fu_263_vnew_1_ce1),
    .vnew_1_q1(vnew_1_q1),
    .g_1_address0(grp_update_linear_cost_4_fu_263_g_1_address0),
    .g_1_ce0(grp_update_linear_cost_4_fu_263_g_1_ce0),
    .g_1_q0(g_1_q0),
    .g_1_address1(grp_update_linear_cost_4_fu_263_g_1_address1),
    .g_1_ce1(grp_update_linear_cost_4_fu_263_g_1_ce1),
    .g_1_q1(g_1_q1),
    .Xref_1_address0(grp_update_linear_cost_4_fu_263_Xref_1_address0),
    .Xref_1_ce0(grp_update_linear_cost_4_fu_263_Xref_1_ce0),
    .Xref_1_q0(Xref_1_q0),
    .Xref_1_address1(grp_update_linear_cost_4_fu_263_Xref_1_address1),
    .Xref_1_ce1(grp_update_linear_cost_4_fu_263_Xref_1_ce1),
    .Xref_1_q1(Xref_1_q1),
    .p_1_address0(grp_update_linear_cost_4_fu_263_p_1_address0),
    .p_1_ce0(grp_update_linear_cost_4_fu_263_p_1_ce0),
    .p_1_we0(grp_update_linear_cost_4_fu_263_p_1_we0),
    .p_1_d0(grp_update_linear_cost_4_fu_263_p_1_d0),
    .p_1_q0(p_1_q0),
    .p_1_address1(grp_update_linear_cost_4_fu_263_p_1_address1),
    .p_1_ce1(grp_update_linear_cost_4_fu_263_p_1_ce1),
    .p_1_we1(grp_update_linear_cost_4_fu_263_p_1_we1),
    .p_1_d1(grp_update_linear_cost_4_fu_263_p_1_d1),
    .p_1_q1(p_1_q1),
    .tiny_x1_address0(grp_update_linear_cost_4_fu_263_tiny_x1_address0),
    .tiny_x1_ce0(grp_update_linear_cost_4_fu_263_tiny_x1_ce0),
    .tiny_x1_we0(grp_update_linear_cost_4_fu_263_tiny_x1_we0),
    .tiny_x1_d0(grp_update_linear_cost_4_fu_263_tiny_x1_d0),
    .tiny_x1_q0(tiny_x1_q0),
    .tiny_rho(tiny_rho),
    .tiny_x2_address0(grp_update_linear_cost_4_fu_263_tiny_x2_address0),
    .tiny_x2_ce0(grp_update_linear_cost_4_fu_263_tiny_x2_ce0),
    .tiny_x2_we0(grp_update_linear_cost_4_fu_263_tiny_x2_we0),
    .tiny_x2_d0(grp_update_linear_cost_4_fu_263_tiny_x2_d0),
    .tiny_x2_q0(tiny_x2_q0),
    .PinfT_1_address0(grp_update_linear_cost_4_fu_263_PinfT_1_address0),
    .PinfT_1_ce0(grp_update_linear_cost_4_fu_263_PinfT_1_ce0),
    .PinfT_1_q0(PinfT_1_q0),
    .PinfT_1_address1(grp_update_linear_cost_4_fu_263_PinfT_1_address1),
    .PinfT_1_ce1(grp_update_linear_cost_4_fu_263_PinfT_1_ce1),
    .PinfT_1_q1(PinfT_1_q1),
    .tiny_x3_address0(grp_update_linear_cost_4_fu_263_tiny_x3_address0),
    .tiny_x3_ce0(grp_update_linear_cost_4_fu_263_tiny_x3_ce0),
    .tiny_x3_we0(grp_update_linear_cost_4_fu_263_tiny_x3_we0),
    .tiny_x3_d0(grp_update_linear_cost_4_fu_263_tiny_x3_d0),
    .tiny_x3_q0(tiny_x3_q0),
    .grp_fu_303_p_din0(grp_update_linear_cost_4_fu_263_grp_fu_303_p_din0),
    .grp_fu_303_p_din1(grp_update_linear_cost_4_fu_263_grp_fu_303_p_din1),
    .grp_fu_303_p_opcode(grp_update_linear_cost_4_fu_263_grp_fu_303_p_opcode),
    .grp_fu_303_p_dout0(grp_fu_303_p2),
    .grp_fu_303_p_ce(grp_update_linear_cost_4_fu_263_grp_fu_303_p_ce)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28 grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_ready),
    .q_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_q_1_address0),
    .q_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_q_1_ce0),
    .q_1_q0(q_1_q0),
    .s2_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s2_1_address0),
    .s2_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s2_1_ce0),
    .s2_1_q0(s2_1_q0),
    .s1_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_address0),
    .s1_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_ce0),
    .s1_1_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_we0),
    .s1_1_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_d0),
    .grp_fu_303_p_din0(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_din0),
    .grp_fu_303_p_din1(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_din1),
    .grp_fu_303_p_opcode(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_opcode),
    .grp_fu_303_p_dout0(grp_fu_303_p2),
    .grp_fu_303_p_ce(grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_ce)
);

tracking_update_linear_cost_Pipeline_VITIS_LOOP_100_1 grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start),
    .ap_done(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_done),
    .ap_idle(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_idle),
    .ap_ready(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_ready),
    .s1_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_s1_1_address0),
    .s1_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_s1_1_ce0),
    .s1_1_q0(s1_1_q0),
    .q_1_address0(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_address0),
    .q_1_ce0(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_ce0),
    .q_1_we0(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_we0),
    .q_1_d0(grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_d0)
);

tracking_faddfsub_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_2_full_dsp_1_U209(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_303_p0),
    .din1(grp_fu_303_p1),
    .opcode(grp_fu_303_opcode),
    .ce(grp_fu_303_ce),
    .dout(grp_fu_303_p2)
);

tracking_fmul_32ns_32ns_32_1_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_1_max_dsp_1_U210(
    .din0(m1_1_q0),
    .din1(bitcast_ln116_1_reg_539),
    .dout(mul5_i_i_fu_310_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_4_fu_263_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_update_linear_cost_4_fu_263_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_4_fu_263_ap_ready == 1'b1)) begin
            grp_update_linear_cost_4_fu_263_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln215_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln215_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln215_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start_reg <= 1'b1;
        end else if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_ready == 1'b1)) begin
            grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln167_fu_323_p2 == 1'd1))) begin
        i_11_fu_114 <= 4'd0;
    end else if (((icmp_ln160_fu_429_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        i_11_fu_114 <= add_ln159_reg_580;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln159_fu_400_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        i_12_fu_118 <= 4'd0;
    end else if (((icmp_ln215_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        i_12_fu_118 <= add_ln215_fu_464_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_102 <= 4'd0;
    end else if (((icmp_ln168_fu_370_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_fu_102 <= add_ln167_reg_517;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln159_fu_400_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        j_8_reg_193 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        j_8_reg_193 <= add_ln160_reg_600;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln167_fu_323_p2 == 1'd0))) begin
        j_reg_182 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        j_reg_182 <= add_ln168_reg_547;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln159_reg_580 <= add_ln159_fu_406_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln160_reg_600 <= add_ln160_fu_435_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln167_reg_517 <= add_ln167_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln168_reg_547 <= add_ln168_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln167_fu_323_p2 == 1'd1))) begin
        bitcast_ln116_1_reg_539 <= bitcast_ln116_1_fu_357_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln215_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        empty_66_reg_623[6 : 2] <= empty_66_fu_494_p2[6 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul5_i_i_reg_615 <= mul5_i_i_fu_310_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln167_fu_323_p2 == 1'd0))) begin
        tmp_reg_522[5 : 2] <= tmp_fu_335_p3[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln159_fu_400_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_s_reg_585[5 : 2] <= tmp_s_fu_412_p3[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln160_fu_429_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        zext_ln161_reg_605[5 : 0] <= zext_ln161_fu_446_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln168_fu_370_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        zext_ln169_reg_552[5 : 0] <= zext_ln169_fu_387_p1[5 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        Xref_1_address0 = grp_update_linear_cost_4_fu_263_Xref_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        Xref_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_address0;
    end else begin
        Xref_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        Xref_1_address1 = grp_update_linear_cost_4_fu_263_Xref_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        Xref_1_address1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_address1;
    end else begin
        Xref_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        Xref_1_ce0 = grp_update_linear_cost_4_fu_263_Xref_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        Xref_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_ce0;
    end else begin
        Xref_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        Xref_1_ce1 = grp_update_linear_cost_4_fu_263_Xref_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        Xref_1_ce1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_Xref_1_ce1;
    end else begin
        Xref_1_ce1 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state11_on_subcall_done)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state20_on_subcall_done)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        g_1_address0 = grp_update_linear_cost_4_fu_263_g_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        g_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_g_1_address0;
    end else begin
        g_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        g_1_ce0 = grp_update_linear_cost_4_fu_263_g_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        g_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_g_1_ce0;
    end else begin
        g_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        g_1_ce1 = grp_update_linear_cost_4_fu_263_g_1_ce1;
    end else begin
        g_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_303_ce = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_303_ce = grp_update_linear_cost_4_fu_263_grp_fu_303_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_303_ce = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_ce;
    end else begin
        grp_fu_303_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_303_opcode = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_303_opcode = grp_update_linear_cost_4_fu_263_grp_fu_303_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_303_opcode = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_303_opcode = 2'd1;
    end else begin
        grp_fu_303_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_303_p0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_303_p0 = grp_update_linear_cost_4_fu_263_grp_fu_303_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_303_p0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_303_p0 = znew_1_q0;
    end else begin
        grp_fu_303_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_303_p1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_grp_fu_303_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_303_p1 = grp_update_linear_cost_4_fu_263_grp_fu_303_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_303_p1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_grp_fu_303_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_303_p1 = y_1_q0;
    end else begin
        grp_fu_303_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        m1_1_address0 = zext_ln161_fu_446_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        m1_1_address0 = zext_ln169_reg_552;
    end else begin
        m1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7))) begin
        m1_1_ce0 = 1'b1;
    end else begin
        m1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        m1_1_we0 = 1'b1;
    end else begin
        m1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        q_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        q_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_q_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        q_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_address0;
    end else begin
        q_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        q_1_address1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_1_address1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_address1;
    end else begin
        q_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        q_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        q_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_q_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        q_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_ce0;
    end else begin
        q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        q_1_ce1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_1_ce1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_1_ce1;
    end else begin
        q_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        q_1_d0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        q_1_d0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_d0;
    end else begin
        q_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        q_1_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_q_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        q_1_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_we0;
    end else begin
        q_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        q_1_we1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_we1;
    end else begin
        q_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        q_col_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        q_col_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_col_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_address0;
    end else begin
        q_col_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        q_col_address1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_col_address1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_address1;
    end else begin
        q_col_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        q_col_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        q_col_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_col_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_ce0;
    end else begin
        q_col_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        q_col_ce1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_col_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_col_ce1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_ce1;
    end else begin
        q_col_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        q_col_d0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_col_d0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_d0;
    end else begin
        q_col_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        q_col_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_q_col_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        q_col_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_we0;
    end else begin
        q_col_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        q_col_we1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_q_col_we1;
    end else begin
        q_col_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        r_1_ce0 = 1'b1;
    end else begin
        r_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        r_1_we0 = 1'b1;
    end else begin
        r_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        s1_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_s1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        s1_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        s1_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        s1_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_address0;
    end else begin
        s1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        s1_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_s1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        s1_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        s1_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        s1_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_ce0;
    end else begin
        s1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s1_1_d0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        s1_1_d0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_d0;
    end else begin
        s1_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s1_1_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s1_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        s1_1_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_s1_1_we0;
    end else begin
        s1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s2_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        s2_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_address0;
    end else begin
        s2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s2_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_s2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        s2_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_ce0;
    end else begin
        s2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        s2_1_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_we0;
    end else begin
        s2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tiny_x1_address0 = grp_update_linear_cost_4_fu_263_tiny_x1_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        tiny_x1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_tiny_x1_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        tiny_x1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_address0;
    end else begin
        tiny_x1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tiny_x1_ce0 = grp_update_linear_cost_4_fu_263_tiny_x1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        tiny_x1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_tiny_x1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        tiny_x1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_ce0;
    end else begin
        tiny_x1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tiny_x1_d0 = grp_update_linear_cost_4_fu_263_tiny_x1_d0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        tiny_x1_d0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_d0;
    end else begin
        tiny_x1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tiny_x1_we0 = grp_update_linear_cost_4_fu_263_tiny_x1_we0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        tiny_x1_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_x1_we0;
    end else begin
        tiny_x1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        vnew_1_address0 = grp_update_linear_cost_4_fu_263_vnew_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        vnew_1_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_vnew_1_address0;
    end else begin
        vnew_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        vnew_1_ce0 = grp_update_linear_cost_4_fu_263_vnew_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        vnew_1_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_vnew_1_ce0;
    end else begin
        vnew_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        vnew_1_ce1 = grp_update_linear_cost_4_fu_263_vnew_1_ce1;
    end else begin
        vnew_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        xref_col_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_xref_col_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        xref_col_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_address0;
    end else begin
        xref_col_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        xref_col_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_xref_col_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        xref_col_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_ce0;
    end else begin
        xref_col_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        xref_col_ce1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_ce1;
    end else begin
        xref_col_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        xref_col_we0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_we0;
    end else begin
        xref_col_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        xref_col_we1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_xref_col_we1;
    end else begin
        xref_col_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_1_ce0 = 1'b1;
    end else begin
        y_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        znew_1_ce0 = 1'b1;
    end else begin
        znew_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln167_fu_323_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln168_fu_370_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln159_fu_400_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln160_fu_429_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln215_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((1'b0 == ap_block_state20_on_subcall_done) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign PinfT_1_address0 = grp_update_linear_cost_4_fu_263_PinfT_1_address0;

assign PinfT_1_address1 = grp_update_linear_cost_4_fu_263_PinfT_1_address1;

assign PinfT_1_ce0 = grp_update_linear_cost_4_fu_263_PinfT_1_ce0;

assign PinfT_1_ce1 = grp_update_linear_cost_4_fu_263_PinfT_1_ce1;

assign add_ln159_fu_406_p2 = (i_11_fu_114 + 4'd1);

assign add_ln160_fu_435_p2 = (j_8_reg_193 + 3'd1);

assign add_ln161_fu_441_p2 = (zext_ln160_fu_425_p1 + tmp_s_reg_585);

assign add_ln167_fu_329_p2 = (i_fu_102 + 4'd1);

assign add_ln168_fu_376_p2 = (j_reg_182 + 3'd1);

assign add_ln169_fu_382_p2 = (zext_ln168_fu_366_p1 + tmp_reg_522);

assign add_ln215_fu_464_p2 = (i_12_fu_118 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11_on_subcall_done = ((grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_done == 1'b0) | (grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state20_on_subcall_done = ((grp_update_linear_cost_4_fu_263_ap_done == 1'b0) | (grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_done == 1'b0));
end

assign bitcast_ln116_1_fu_357_p1 = xor_ln116_fu_351_p2;

assign bitcast_ln116_fu_347_p1 = tiny_rho;

assign empty_65_fu_470_p1 = i_12_fu_118[2:0];

assign empty_66_fu_494_p2 = (p_shl_fu_474_p3 - p_shl1_cast_fu_490_p1);

assign g_1_address1 = grp_update_linear_cost_4_fu_263_g_1_address1;

assign grp_update_linear_cost_4_fu_263_ap_start = grp_update_linear_cost_4_fu_263_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_100_1_fu_295_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_28_fu_285_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_167_1_VITIS_LOOP_168_2_fu_220_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_72_2_fu_239_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_17_fu_212_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_86_1_fu_204_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_ap_start_reg;

assign grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_ap_start_reg;

assign icmp_ln159_fu_400_p2 = ((i_11_fu_114 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln160_fu_429_p2 = ((j_8_reg_193 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_323_p2 = ((i_fu_102 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_370_p2 = ((j_reg_182 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_458_p2 = ((i_12_fu_118 == 4'd10) ? 1'b1 : 1'b0);

assign m1_1_d0 = grp_fu_303_p2;

assign p_1_address0 = grp_update_linear_cost_4_fu_263_p_1_address0;

assign p_1_address1 = grp_update_linear_cost_4_fu_263_p_1_address1;

assign p_1_ce0 = grp_update_linear_cost_4_fu_263_p_1_ce0;

assign p_1_ce1 = grp_update_linear_cost_4_fu_263_p_1_ce1;

assign p_1_d0 = grp_update_linear_cost_4_fu_263_p_1_d0;

assign p_1_d1 = grp_update_linear_cost_4_fu_263_p_1_d1;

assign p_1_we0 = grp_update_linear_cost_4_fu_263_p_1_we0;

assign p_1_we1 = grp_update_linear_cost_4_fu_263_p_1_we1;

assign p_shl1_cast_fu_490_p1 = p_shl1_fu_482_p3;

assign p_shl1_fu_482_p3 = {{i_12_fu_118}, {2'd0}};

assign p_shl_fu_474_p3 = {{empty_65_fu_470_p1}, {4'd0}};

assign q_1_d1 = grp_update_linear_cost_Pipeline_VITIS_LOOP_93_1_fu_246_q_1_d1;

assign r_1_address0 = zext_ln161_reg_605;

assign r_1_d0 = mul5_i_i_reg_615;

assign s2_1_d0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_159_1_VITIS_LOOP_160_2_fu_254_s2_1_d0;

assign tiny_Q_address0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_Q_address0;

assign tiny_Q_ce0 = grp_update_linear_cost_Pipeline_VITIS_LOOP_99_2_fu_230_tiny_Q_ce0;

assign tiny_x2_address0 = grp_update_linear_cost_4_fu_263_tiny_x2_address0;

assign tiny_x2_ce0 = grp_update_linear_cost_4_fu_263_tiny_x2_ce0;

assign tiny_x2_d0 = grp_update_linear_cost_4_fu_263_tiny_x2_d0;

assign tiny_x2_we0 = grp_update_linear_cost_4_fu_263_tiny_x2_we0;

assign tiny_x3_address0 = grp_update_linear_cost_4_fu_263_tiny_x3_address0;

assign tiny_x3_ce0 = grp_update_linear_cost_4_fu_263_tiny_x3_ce0;

assign tiny_x3_d0 = grp_update_linear_cost_4_fu_263_tiny_x3_d0;

assign tiny_x3_we0 = grp_update_linear_cost_4_fu_263_tiny_x3_we0;

assign tmp_fu_335_p3 = {{i_fu_102}, {2'd0}};

assign tmp_s_fu_412_p3 = {{i_11_fu_114}, {2'd0}};

assign vnew_1_address1 = grp_update_linear_cost_4_fu_263_vnew_1_address1;

assign xor_ln116_fu_351_p2 = (bitcast_ln116_fu_347_p1 ^ 32'd2147483648);

assign y_1_address0 = zext_ln169_fu_387_p1;

assign zext_ln160_fu_425_p1 = j_8_reg_193;

assign zext_ln161_fu_446_p1 = add_ln161_fu_441_p2;

assign zext_ln168_fu_366_p1 = j_reg_182;

assign zext_ln169_fu_387_p1 = add_ln169_fu_382_p2;

assign znew_1_address0 = zext_ln169_fu_387_p1;

always @ (posedge ap_clk) begin
    tmp_reg_522[1:0] <= 2'b00;
    zext_ln169_reg_552[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    tmp_s_reg_585[1:0] <= 2'b00;
    zext_ln161_reg_605[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    empty_66_reg_623[1:0] <= 2'b00;
end

endmodule //tracking_update_linear_cost
