// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tracking_tracking_Pipeline_VITIS_LOOP_109_114 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_min_1_address0,
        x_min_1_ce0,
        x_min_1_we0,
        x_min_1_d0,
        x_min_1_address1,
        x_min_1_ce1,
        x_min_1_we1,
        x_min_1_d1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] x_min_1_address0;
output   x_min_1_ce0;
output   x_min_1_we0;
output  [31:0] x_min_1_d0;
output  [6:0] x_min_1_address1;
output   x_min_1_ce1;
output   x_min_1_we1;
output  [31:0] x_min_1_d1;

reg ap_idle;
reg[6:0] x_min_1_address0;
reg x_min_1_ce0;
reg x_min_1_we0;
reg[6:0] x_min_1_address1;
reg x_min_1_ce1;
reg x_min_1_we1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln109_2_fu_91_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state2;
wire    ap_block_state2_pp0_stage1_iter0;
reg   [6:0] i_27_reg_151;
wire   [63:0] i_29_cast14_fu_97_p1;
wire   [63:0] zext_ln111_fu_108_p1;
wire   [63:0] zext_ln111_3_fu_129_p1;
wire   [63:0] zext_ln111_4_fu_139_p1;
reg   [6:0] i_fu_36;
wire   [6:0] add_ln109_fu_113_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_27;
wire   [6:0] or_ln109_fu_102_p2;
wire   [6:0] or_ln109_4_fu_124_p2;
wire   [6:0] or_ln109_5_fu_134_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

tracking_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln109_2_fu_91_p2 == 1'd1)) begin
            i_fu_36 <= add_ln109_fu_113_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_36 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        i_27_reg_151 <= ap_sig_allocacmp_i_27;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln109_2_fu_91_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_27 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_27 = i_fu_36;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_min_1_address0 = zext_ln111_4_fu_139_p1;
    end else if (((icmp_ln109_2_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_min_1_address0 = zext_ln111_fu_108_p1;
    end else begin
        x_min_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_min_1_address1 = zext_ln111_3_fu_129_p1;
    end else if (((icmp_ln109_2_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_min_1_address1 = i_29_cast14_fu_97_p1;
    end else begin
        x_min_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln109_2_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1)))) begin
        x_min_1_ce0 = 1'b1;
    end else begin
        x_min_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln109_2_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1)))) begin
        x_min_1_ce1 = 1'b1;
    end else begin
        x_min_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln109_2_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1)))) begin
        x_min_1_we0 = 1'b1;
    end else begin
        x_min_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln109_2_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1)))) begin
        x_min_1_we1 = 1'b1;
    end else begin
        x_min_1_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln109_2_fu_91_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_113_p2 = (ap_sig_allocacmp_i_27 + 7'd4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_29_cast14_fu_97_p1 = ap_sig_allocacmp_i_27;

assign icmp_ln109_2_fu_91_p2 = ((ap_sig_allocacmp_i_27 < 7'd120) ? 1'b1 : 1'b0);

assign or_ln109_4_fu_124_p2 = (i_27_reg_151 | 7'd2);

assign or_ln109_5_fu_134_p2 = (i_27_reg_151 | 7'd3);

assign or_ln109_fu_102_p2 = (ap_sig_allocacmp_i_27 | 7'd1);

assign x_min_1_d0 = 32'd3231711232;

assign x_min_1_d1 = 32'd3231711232;

assign zext_ln111_3_fu_129_p1 = or_ln109_4_fu_124_p2;

assign zext_ln111_4_fu_139_p1 = or_ln109_5_fu_134_p2;

assign zext_ln111_fu_108_p1 = or_ln109_fu_102_p2;

endmodule //tracking_tracking_Pipeline_VITIS_LOOP_109_114
