// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tracking_forward_pass_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i,
        x_1_address0,
        x_1_ce0,
        x_1_we0,
        x_1_d0,
        x_1_q0,
        x_1_address1,
        x_1_ce1,
        x_1_q1,
        u_1_address0,
        u_1_ce0,
        u_1_q0,
        u_1_address1,
        u_1_ce1,
        u_1_q1,
        Adyn_1_address0,
        Adyn_1_ce0,
        Adyn_1_q0,
        Adyn_1_address1,
        Adyn_1_ce1,
        Adyn_1_q1,
        tiny_x1_address0,
        tiny_x1_ce0,
        tiny_x1_we0,
        tiny_x1_d0,
        tiny_x1_q0,
        Bdyn_1_address0,
        Bdyn_1_ce0,
        Bdyn_1_q0,
        Bdyn_1_address1,
        Bdyn_1_ce1,
        Bdyn_1_q1,
        tiny_x2_address0,
        tiny_x2_ce0,
        tiny_x2_we0,
        tiny_x2_d0,
        tiny_x2_q0
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] i;
output  [6:0] x_1_address0;
output   x_1_ce0;
output   x_1_we0;
output  [31:0] x_1_d0;
input  [31:0] x_1_q0;
output  [6:0] x_1_address1;
output   x_1_ce1;
input  [31:0] x_1_q1;
output  [5:0] u_1_address0;
output   u_1_ce0;
input  [31:0] u_1_q0;
output  [5:0] u_1_address1;
output   u_1_ce1;
input  [31:0] u_1_q1;
output  [7:0] Adyn_1_address0;
output   Adyn_1_ce0;
input  [31:0] Adyn_1_q0;
output  [7:0] Adyn_1_address1;
output   Adyn_1_ce1;
input  [31:0] Adyn_1_q1;
output  [3:0] tiny_x1_address0;
output   tiny_x1_ce0;
output   tiny_x1_we0;
output  [31:0] tiny_x1_d0;
input  [31:0] tiny_x1_q0;
output  [5:0] Bdyn_1_address0;
output   Bdyn_1_ce0;
input  [31:0] Bdyn_1_q0;
output  [5:0] Bdyn_1_address1;
output   Bdyn_1_ce1;
input  [31:0] Bdyn_1_q1;
output  [3:0] tiny_x2_address0;
output   tiny_x2_ce0;
output   tiny_x2_we0;
output  [31:0] tiny_x2_d0;
input  [31:0] tiny_x2_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] x_1_address0;
reg x_1_ce0;
reg x_1_we0;
reg[6:0] x_1_address1;
reg x_1_ce1;
reg[5:0] u_1_address0;
reg u_1_ce0;
reg[5:0] u_1_address1;
reg u_1_ce1;
reg[3:0] tiny_x1_address0;
reg tiny_x1_ce0;
reg tiny_x1_we0;
reg[3:0] tiny_x2_address0;
reg tiny_x2_ce0;
reg tiny_x2_we0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] p_shl1_fu_310_p3;
reg   [5:0] p_shl1_reg_369;
wire   [6:0] mul_i_fu_322_p2;
reg   [6:0] mul_i_reg_377;
wire    ap_CS_fsm_state3;
wire   [31:0] x_col_q1;
reg   [31:0] x_col_load_reg_393;
wire    ap_CS_fsm_state4;
wire   [31:0] x_col_q0;
reg   [31:0] x_col_load_1_reg_398;
reg   [31:0] x_col_load_2_reg_413;
wire    ap_CS_fsm_state5;
reg   [31:0] x_col_load_3_reg_418;
reg   [31:0] x_col_load_4_reg_433;
wire    ap_CS_fsm_state6;
reg   [31:0] x_col_load_5_reg_438;
wire    ap_CS_fsm_state7;
reg   [31:0] x_col_load_6_reg_463;
reg   [31:0] x_col_load_7_reg_468;
reg   [31:0] u_1_load_reg_483;
wire    ap_CS_fsm_state8;
reg   [31:0] u_1_load_4_reg_488;
reg   [31:0] x_col_load_8_reg_503;
reg   [31:0] x_col_load_9_reg_508;
reg   [31:0] u_1_load_5_reg_523;
wire    ap_CS_fsm_state9;
reg   [31:0] u_1_load_6_reg_528;
wire   [6:0] mul_i12_fu_363_p2;
reg   [6:0] mul_i12_reg_533;
reg   [31:0] x_col_load_10_reg_539;
reg   [31:0] x_col_load_11_reg_544;
reg   [3:0] x_col_address0;
reg    x_col_ce0;
reg    x_col_we0;
reg   [3:0] x_col_address1;
reg    x_col_ce1;
reg    x_col_we1;
reg   [3:0] x_col_p1_address0;
reg    x_col_p1_ce0;
reg    x_col_p1_we0;
reg   [31:0] x_col_p1_d0;
wire   [31:0] x_col_p1_q0;
reg   [3:0] x_col_p1_address1;
reg    x_col_p1_ce1;
reg    x_col_p1_we1;
wire   [31:0] x_col_p1_q1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_done;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_idle;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_ready;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_ce0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_we0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_d0;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_address1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_ce1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_we1;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_d1;
wire   [6:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_ce0;
wire   [6:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_address1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_ce1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_done;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_idle;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_ready;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_ce0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_we0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_d0;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_address1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_ce1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_we1;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_d1;
wire   [6:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_ce0;
wire   [6:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_address1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_ce1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_done;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_idle;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_ready;
wire   [7:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_ce0;
wire   [7:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_address1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_ce1;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_ce0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_we0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_d0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_done;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_idle;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_ready;
wire   [5:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_ce0;
wire   [5:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_address1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_ce1;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_ce0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_we0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_d0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_din0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_din1;
wire   [1:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_opcode;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_ce;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_done;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_idle;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_ready;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_ce0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_we0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_d0;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x1_ce0;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x2_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x2_ce0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_din0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_din1;
wire   [1:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_opcode;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_ce;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_idle;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_ready;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_ce0;
wire   [3:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_address1;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_ce1;
wire   [6:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_address0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_ce0;
wire    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_we0;
wire   [31:0] grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_d0;
reg    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start_reg;
reg    grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start_reg;
reg    grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln88_fu_329_p1;
wire   [63:0] zext_ln88_51_fu_338_p1;
wire   [63:0] zext_ln88_52_fu_348_p1;
wire   [63:0] zext_ln88_53_fu_358_p1;
wire   [2:0] empty_fu_298_p1;
wire   [6:0] p_shl_fu_302_p3;
wire   [6:0] p_shl1_cast_fu_318_p1;
wire   [5:0] or_ln88_fu_333_p2;
wire   [5:0] or_ln88_1_fu_343_p2;
wire   [5:0] or_ln88_2_fu_353_p2;
wire   [31:0] grp_fu_549_p2;
reg   [31:0] grp_fu_549_p0;
reg   [31:0] grp_fu_549_p1;
reg    grp_fu_549_ce;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_block_state10_on_subcall_done;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start_reg = 1'b0;
#0 grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start_reg = 1'b0;
#0 grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start_reg = 1'b0;
#0 grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start_reg = 1'b0;
#0 grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start_reg = 1'b0;
#0 grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg = 1'b0;
end

tracking_forward_pass_2_x_col_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
x_col_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(x_col_address0),
    .ce0(x_col_ce0),
    .we0(x_col_we0),
    .d0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_d0),
    .q0(x_col_q0),
    .address1(x_col_address1),
    .ce1(x_col_ce1),
    .we1(x_col_we1),
    .d1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_d1),
    .q1(x_col_q1)
);

tracking_forward_pass_2_x_col_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
x_col_p1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(x_col_p1_address0),
    .ce0(x_col_p1_ce0),
    .we0(x_col_p1_we0),
    .d0(x_col_p1_d0),
    .q0(x_col_p1_q0),
    .address1(x_col_p1_address1),
    .ce1(x_col_p1_ce1),
    .we1(x_col_p1_we1),
    .d1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_d1),
    .q1(x_col_p1_q1)
);

tracking_forward_pass_2_Pipeline_VITIS_LOOP_86_1 grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start),
    .ap_done(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_done),
    .ap_idle(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_idle),
    .ap_ready(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_ready),
    .mul_i(mul_i_reg_377),
    .x_col_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_address0),
    .x_col_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_ce0),
    .x_col_we0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_we0),
    .x_col_d0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_d0),
    .x_col_address1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_address1),
    .x_col_ce1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_ce1),
    .x_col_we1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_we1),
    .x_col_d1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_d1),
    .x_1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_address0),
    .x_1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_ce0),
    .x_1_q0(x_1_q0),
    .x_1_address1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_address1),
    .x_1_ce1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_ce1),
    .x_1_q1(x_1_q1)
);

tracking_forward_pass_2_Pipeline_VITIS_LOOP_86_126 grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start),
    .ap_done(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_done),
    .ap_idle(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_idle),
    .ap_ready(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_ready),
    .mul_i12(mul_i12_reg_533),
    .x_col_p1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_address0),
    .x_col_p1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_ce0),
    .x_col_p1_we0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_we0),
    .x_col_p1_d0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_d0),
    .x_col_p1_address1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_address1),
    .x_col_p1_ce1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_ce1),
    .x_col_p1_we1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_we1),
    .x_col_p1_d1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_d1),
    .x_1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_address0),
    .x_1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_ce0),
    .x_1_q0(x_1_q0),
    .x_1_address1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_address1),
    .x_1_ce1(grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_ce1),
    .x_1_q1(x_1_q1)
);

tracking_forward_pass_2_Pipeline_VITIS_LOOP_133_1 grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start),
    .ap_done(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_done),
    .ap_idle(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_idle),
    .ap_ready(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_ready),
    .x_col_load(x_col_load_reg_393),
    .x_col_load_1(x_col_load_1_reg_398),
    .x_col_load_2(x_col_load_2_reg_413),
    .x_col_load_3(x_col_load_3_reg_418),
    .x_col_load_4(x_col_load_4_reg_433),
    .x_col_load_5(x_col_load_5_reg_438),
    .x_col_load_6(x_col_load_6_reg_463),
    .x_col_load_7(x_col_load_7_reg_468),
    .x_col_load_8(x_col_load_8_reg_503),
    .x_col_load_9(x_col_load_9_reg_508),
    .x_col_load_10(x_col_load_10_reg_539),
    .x_col_load_11(x_col_load_11_reg_544),
    .Adyn_1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_address0),
    .Adyn_1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_ce0),
    .Adyn_1_q0(Adyn_1_q0),
    .Adyn_1_address1(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_address1),
    .Adyn_1_ce1(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_ce1),
    .Adyn_1_q1(Adyn_1_q1),
    .tiny_x1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_address0),
    .tiny_x1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_ce0),
    .tiny_x1_we0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_we0),
    .tiny_x1_d0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_d0)
);

tracking_forward_pass_2_Pipeline_VITIS_LOOP_133_127 grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start),
    .ap_done(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_done),
    .ap_idle(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_idle),
    .ap_ready(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_ready),
    .u_1_load(u_1_load_reg_483),
    .u_1_load_4(u_1_load_4_reg_488),
    .u_1_load_5(u_1_load_5_reg_523),
    .u_1_load_6(u_1_load_6_reg_528),
    .Bdyn_1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_address0),
    .Bdyn_1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_ce0),
    .Bdyn_1_q0(Bdyn_1_q0),
    .Bdyn_1_address1(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_address1),
    .Bdyn_1_ce1(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_ce1),
    .Bdyn_1_q1(Bdyn_1_q1),
    .tiny_x2_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_address0),
    .tiny_x2_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_ce0),
    .tiny_x2_we0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_we0),
    .tiny_x2_d0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_d0),
    .grp_fu_549_p_din0(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_din0),
    .grp_fu_549_p_din1(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_din1),
    .grp_fu_549_p_opcode(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_opcode),
    .grp_fu_549_p_dout0(grp_fu_549_p2),
    .grp_fu_549_p_ce(grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_ce)
);

tracking_forward_pass_2_Pipeline_VITIS_LOOP_177_2 grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start),
    .ap_done(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_done),
    .ap_idle(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_idle),
    .ap_ready(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_ready),
    .x_col_p1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_address0),
    .x_col_p1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_ce0),
    .x_col_p1_we0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_we0),
    .x_col_p1_d0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_d0),
    .tiny_x1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x1_address0),
    .tiny_x1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x1_ce0),
    .tiny_x1_q0(tiny_x1_q0),
    .tiny_x2_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x2_address0),
    .tiny_x2_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x2_ce0),
    .tiny_x2_q0(tiny_x2_q0),
    .grp_fu_549_p_din0(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_din0),
    .grp_fu_549_p_din1(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_din1),
    .grp_fu_549_p_opcode(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_opcode),
    .grp_fu_549_p_dout0(grp_fu_549_p2),
    .grp_fu_549_p_ce(grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_ce)
);

tracking_forward_pass_2_Pipeline_VITIS_LOOP_93_1 grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start),
    .ap_done(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done),
    .ap_idle(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_idle),
    .ap_ready(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_ready),
    .x_col_p1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_address0),
    .x_col_p1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_ce0),
    .x_col_p1_q0(x_col_p1_q0),
    .x_col_p1_address1(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_address1),
    .x_col_p1_ce1(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_ce1),
    .x_col_p1_q1(x_col_p1_q1),
    .mul_i12(mul_i12_reg_533),
    .x_1_address0(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_address0),
    .x_1_ce0(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_ce0),
    .x_1_we0(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_we0),
    .x_1_d0(grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_d0)
);

tracking_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_549_p0),
    .din1(grp_fu_549_p1),
    .ce(grp_fu_549_ce),
    .dout(grp_fu_549_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start_reg <= 1'b1;
        end else if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_ready == 1'b1)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start_reg <= 1'b1;
        end else if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_ready == 1'b1)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start_reg <= 1'b1;
        end else if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_ready == 1'b1)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start_reg <= 1'b1;
        end else if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_ready == 1'b1)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_ready == 1'b1)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg <= 1'b1;
        end else if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_ready == 1'b1)) begin
            grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        mul_i12_reg_533[6 : 2] <= mul_i12_fu_363_p2[6 : 2];
        u_1_load_5_reg_523 <= u_1_q1;
        u_1_load_6_reg_528 <= u_1_q0;
        x_col_load_10_reg_539 <= x_col_q1;
        x_col_load_11_reg_544 <= x_col_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        mul_i_reg_377[6 : 2] <= mul_i_fu_322_p2[6 : 2];
        p_shl1_reg_369[5 : 2] <= p_shl1_fu_310_p3[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        u_1_load_4_reg_488 <= u_1_q0;
        u_1_load_reg_483 <= u_1_q1;
        x_col_load_8_reg_503 <= x_col_q1;
        x_col_load_9_reg_508 <= x_col_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x_col_load_1_reg_398 <= x_col_q0;
        x_col_load_reg_393 <= x_col_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_col_load_2_reg_413 <= x_col_q1;
        x_col_load_3_reg_418 <= x_col_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_col_load_4_reg_433 <= x_col_q1;
        x_col_load_5_reg_438 <= x_col_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        x_col_load_6_reg_463 <= x_col_q1;
        x_col_load_7_reg_468 <= x_col_q0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_549_ce = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_549_ce = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_ce;
    end else begin
        grp_fu_549_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_549_p0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_549_p0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_din0;
    end else begin
        grp_fu_549_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_549_p1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_grp_fu_549_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_549_p1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_grp_fu_549_p_din1;
    end else begin
        grp_fu_549_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tiny_x1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        tiny_x1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_address0;
    end else begin
        tiny_x1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tiny_x1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        tiny_x1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_ce0;
    end else begin
        tiny_x1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tiny_x1_we0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_we0;
    end else begin
        tiny_x1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tiny_x2_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x2_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        tiny_x2_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_address0;
    end else begin
        tiny_x2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tiny_x2_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_tiny_x2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        tiny_x2_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_ce0;
    end else begin
        tiny_x2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tiny_x2_we0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_we0;
    end else begin
        tiny_x2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        u_1_address0 = zext_ln88_53_fu_358_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        u_1_address0 = zext_ln88_51_fu_338_p1;
    end else begin
        u_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        u_1_address1 = zext_ln88_52_fu_348_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        u_1_address1 = zext_ln88_fu_329_p1;
    end else begin
        u_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        u_1_ce0 = 1'b1;
    end else begin
        u_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        u_1_ce1 = 1'b1;
    end else begin
        u_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_address0;
    end else begin
        x_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        x_1_address1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_1_address1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_address1;
    end else begin
        x_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_ce0;
    end else begin
        x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        x_1_ce1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_1_ce1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_1_ce1;
    end else begin
        x_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_1_we0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_we0;
    end else begin
        x_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_col_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        x_col_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_col_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_col_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_col_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_col_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_col_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_address0;
    end else begin
        x_col_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_col_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        x_col_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_col_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_col_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_col_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_col_address1 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_col_address1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_address1;
    end else begin
        x_col_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        x_col_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_col_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_ce0;
    end else begin
        x_col_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        x_col_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_col_ce1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_ce1;
    end else begin
        x_col_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_col_p1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        x_col_p1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_col_p1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_address0;
    end else begin
        x_col_p1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_col_p1_address1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_address1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_col_p1_address1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_address1;
    end else begin
        x_col_p1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_col_p1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        x_col_p1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_col_p1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_ce0;
    end else begin
        x_col_p1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        x_col_p1_ce1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_col_p1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_col_p1_ce1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_ce1;
    end else begin
        x_col_p1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        x_col_p1_d0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_col_p1_d0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_d0;
    end else begin
        x_col_p1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        x_col_p1_we0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_x_col_p1_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_col_p1_we0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_we0;
    end else begin
        x_col_p1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        x_col_p1_we1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_x_col_p1_we1;
    end else begin
        x_col_p1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_col_we0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_we0;
    end else begin
        x_col_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_col_we1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_x_col_we1;
    end else begin
        x_col_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Adyn_1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_address0;

assign Adyn_1_address1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_address1;

assign Adyn_1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_ce0;

assign Adyn_1_ce1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_Adyn_1_ce1;

assign Bdyn_1_address0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_address0;

assign Bdyn_1_address1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_address1;

assign Bdyn_1_ce0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_ce0;

assign Bdyn_1_ce1 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_Bdyn_1_ce1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_done == 1'b0) | (grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_done == 1'b0) | (grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_done == 1'b0));
end

assign empty_fu_298_p1 = i[2:0];

assign grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_ap_start_reg;

assign grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_ap_start_reg;

assign grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start = grp_forward_pass_2_Pipeline_VITIS_LOOP_177_2_fu_281_ap_start_reg;

assign grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_126_fu_237_ap_start_reg;

assign grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start = grp_forward_pass_2_Pipeline_VITIS_LOOP_86_1_fu_228_ap_start_reg;

assign grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_ap_start_reg;

assign mul_i12_fu_363_p2 = (mul_i_reg_377 + 7'd12);

assign mul_i_fu_322_p2 = (p_shl_fu_302_p3 - p_shl1_cast_fu_318_p1);

assign or_ln88_1_fu_343_p2 = (p_shl1_reg_369 | 6'd2);

assign or_ln88_2_fu_353_p2 = (p_shl1_reg_369 | 6'd3);

assign or_ln88_fu_333_p2 = (p_shl1_reg_369 | 6'd1);

assign p_shl1_cast_fu_318_p1 = p_shl1_fu_310_p3;

assign p_shl1_fu_310_p3 = {{i}, {2'd0}};

assign p_shl_fu_302_p3 = {{empty_fu_298_p1}, {4'd0}};

assign tiny_x1_d0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_1_fu_245_tiny_x1_d0;

assign tiny_x2_d0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_133_127_fu_267_tiny_x2_d0;

assign x_1_d0 = grp_forward_pass_2_Pipeline_VITIS_LOOP_93_1_fu_290_x_1_d0;

assign zext_ln88_51_fu_338_p1 = or_ln88_fu_333_p2;

assign zext_ln88_52_fu_348_p1 = or_ln88_1_fu_343_p2;

assign zext_ln88_53_fu_358_p1 = or_ln88_2_fu_353_p2;

assign zext_ln88_fu_329_p1 = p_shl1_reg_369;

always @ (posedge ap_clk) begin
    p_shl1_reg_369[1:0] <= 2'b00;
    mul_i_reg_377[1:0] <= 2'b00;
    mul_i12_reg_533[1:0] <= 2'b00;
end

endmodule //tracking_forward_pass_2
